spring.application.name=attestation3


spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/patients_db

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

server.servlet.context-path=/api

server.
# ????????? Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

#Template files encoding.
spring.thymeleaf.encoding=UTF-8
#Template mode to be applied to templates
spring.thymeleaf.mode=HTML